### ISSUE TITLE
Errors compiling from sources

### ISSUE THREAD

**Issue by MohammadKanan** [m2osw/snapcpp#2]
Hello Alexis,

I am trying to build on Ubuntu bionic (Ubuntu 18.04.4 LTS) , having following issues:
- sudo add-apt-repository ppa:tcpcloud/extra

```
Err:12 http://ppa.launchpad.net/tcpcloud/extra/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
```

**Comment by AlexisWilke** [comment]
The PPA is not to do a build, that's to get the pre-built version of the libraries.

Now, I have nothing to do with `tcpcloud`. You probably want to find the right author.

Maybe `tcpcloud` uses some of the `snapcpp` contribs (libraries) and it got confused?

I offer the [`eventdispatcher`](https://github.com/m2osw/eventdispatcher) library, for example, which allows for TCP, UDP, Unix Signal, timers and a few other things to be managed with the `poll()` command. You can use that to make your system 100% event driven.

**Comment by MohammadKanan** [comment]
Right. I tried the prebuilt first, got that error, then moved to build it following _**developer**_  hints, strangely, however, after 95% of the build  .. I got what I thought a strange error : `‘next’ is not a member of ‘boost’` .. but from first search, I realized its common error with **_yaml_**  , not sure how to solve it as I am not with idea of modifying yaml include files on the host
```
In file included from /usr/include/yaml-cpp/node/iterator.h:13:0,
                 from /usr/include/yaml-cpp/node/impl.h:11,
                 from /usr/include/yaml-cpp/yaml.h:17,
                 from /home/osboxes/qt_Projects/ve/snapwebsites/snapcpp/snapwebsites/snapmanager/plugins/cassandra/cassandra.cpp:65:
/usr/include/yaml-cpp/node/detail/iterator.h: In member function ‘void YAML::detail::iterator_base<V>::increment()’:
/usr/include/yaml-cpp/node/detail/iterator.h:48:54: error: ‘next’ is not a member of ‘boost’
   void increment() { this->base_reference() = boost::next(this->base()); }
                                                      ^~~~
/usr/include/yaml-cpp/node/detail/iterator.h:48:54: note: suggested alternative: ‘get’
   void increment() { this->base_reference() = boost::next(this->base()); }
                                                      ^~~~
                                                      get
make[5]: *** [snapmanager/plugins/cassandra/CMakeFiles/cassandra.dir/cassandra.cpp.o] Error 1
make[4]: *** [snapmanager/plugins/cassandra/CMakeFiles/cassandra.dir/all] Error 2
make[3]: *** [all] Error 2
```

**Comment by AlexisWilke** [comment]
Hmmm... I don't recall such errors.

Did you make sure you had the most recent version of the `snapwebsites` source? The `snapcpp` is not always pointing to the latest.

It is compiling for me on 18.04, so I'm not too sure. Maybe you have a different version of boost installed, somehow. I use the stock version. There are many others, but all have the same version: 1.65.1. Is that what you have too?

    ii  libboost1.65-dev:amd64                         1.65.1+dfsg-0ubuntu5                             amd64        Boost C++ Libraries development files

And for yaml, the version vary depending on the package type:

    ii  libyaml-0-2:amd64                              0.1.7-2ubuntu3                                   amd64        Fast YAML 1.1 parser and emitter library
    ii  libyaml-cpp-dev                                0.5.2-4ubuntu1                                   amd64        YAML parser and emitter for C++ - development files
    ii  libyaml-cpp0.5v5:amd64                         0.5.2-4ubuntu1                                   amd64        YAML parser and emitter for C++
    ii  libyaml-dev:amd64                              0.1.7-2ubuntu3                                   amd64        Fast YAML 1.1 parser and emitter library (development)
